services:
  - type: web
    name: telegram-morning-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_combined.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: gpt-4
      - key: AI_PROVIDER
        value: gemini
      - key: TIMEZONE
        value: America/Mexico_City
      - key: SYNC_GOOGLE_TASKS
        value: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: GOOGLE_CREDENTIALS_PATH
        value: credentials.json
      - key: GOOGLE_TOKEN_PATH
        value: token.json